allowBuilds:
  msw: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
packageExtensions:
  '@hookform/resolvers@*':
    peerDependencies:
      zod: ^3.25.0 || ^4.0.0
